---
title: "comocensus"
output: html_document
date: "2022-10-31"
---

```{r}
library(tidyverse) 
library(tidycensus)
library(dplyr)
library(labeling)
library(scales)
```

### Searching for variables

```{r}
acs2020_var <- load_variables(2020, "acs5", cache=TRUE)

dcs2020_var <- load_variables(2020, "pl", cache=TRUE)
```

### loading my variables 

i ended up following a lot of the chapter on exploring census data via data viz from here. published under cc 4.0 and it was really helpful [https://walker-data.com/census-r/exploring-us-census-data-with-visualization.html]

malepop1_filtered changed the male population values from positive to negative 

```{r}
malepop <- get_acs(geography = "county",
                   variables = "B01001_002",
                   state = "MO",
                   year = 2021,
                   survey = "acs1")

mopop1 <- get_estimates(geography = "county",
                          state = "MO",
                          product = "characteristics",
                          breakdown = c("SEX", "AGEGROUP"),
                          breakdown_labels = TRUE,
                          year = 2019)

mopop1_filtered <- filter(mopop, str_detect(AGEGROUP, "^Age"), 
                  SEX != "Both sexes") %>%
                  mutate(value = ifelse(SEX == "Male", -value, value))

mopop2 <- get_estimates(geography = "county",
                          state = "MO",
                          county = "Boone",
                          product = "characteristics",
                          breakdown = c("SEX", "AGEGROUP"),
                          breakdown_labels = TRUE,
                          year = 2019)

mopop2_filtered <- filter(mopop2, str_detect(AGEGROUP, "^Age"),
                          SEX !="Both sexes") %>% 
                          mutate(value = ifelse(SEX =="Male", -value, value))

```

### Population pyramid for state of Missouri: 

```{r}
ggplot(mopop2_filtered, aes(x = value, y = AGEGROUP, fill = SEX)) + 
  geom_col() + 
  theme_minimal(base_family = "Helvetica", 
                base_size = 12) + 
  scale_x_continuous(labels = ~ number_format(scale = .001, suffix = "k")(abs(.x)), limits = 140000 * c(-1,1)) + 
  scale_y_discrete(labels = ~ str_remove_all(.x, "Age\\s|\\syears")) + 
  labs(x = "", 
       y = "2019 Census Bureau population estimate", 
       title = "Population Pyramid of Missouri", 
       fill = "", 
       caption = "Source: US Census Bureau population estimates")
```
### Boone county population pyramid
```{r}
ggplot(mopop2_filtered, aes(x = value, y = AGEGROUP, fill = SEX)) + 
  geom_col() + 
  theme_minimal(base_family = "Helvetica", 
                base_size = 12) + 
  scale_x_continuous(labels = ~ comma_format(scale = 1)(abs(.x)), limits = 20000 * c(-1,1)) + 
  scale_y_discrete(labels = ~ str_remove_all(.x, "Age\\s|\\syears")) + 
  labs(x = "", 
       y = "2019 Census Bureau population estimate", 
       title = "Population Pyramid of Boone County, Missouri", 
       fill = "", 
       caption = "Source: US Census Bureau population estimates")
```

